name: Release
on:
  workflow_call:
    inputs:
      DOCKER_IMAGE_TAG:
        description: 'Docker Image Tag'
        type: string
        required: true
    secrets:
      DOCKER_IMAGE_TAG:
        description: 'Docker Image Tag'
        required: true

jobs:
  release-tag:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the code
        id: checkout-the-code
        uses: actions/checkout@v3

      - name: Checking Repo and Tag Name
        id: tag-name
        run: |
          echo "docker_tag=$GITHUB_REPOSITORY:${GITHUB_REF#$"refs/tags/"}" >> $GITHUB_OUTPUT

      - name: Create CLI Release
        id: create-cli-release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: |
            CLI Package Docker Image:
            ```
            docker pull ${{ steps.tag-name.outputs.docker_tag }}
            ```
          tag_name: ${{ github.GITHUB_REF }}
          name: ${{ github.GITHUB_REF }}
          draft: false
          prerelease: false