#
# Upload workflow
#

name: Upload

on:
  release:
    types: [created]

jobs:
  upload-asset:
    permissions:
      contents: write
    strategy:
      matrix:
        go-version: [1.18.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checking out the code
        id: checkout-the-code
        uses: actions/checkout@v3

      - name: Set up Go
        id: setup-go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build CLI
        id: build-cli
        run: |
          GOOS=linux GOARCH=amd64 go build -o ./build/linux/onqlave .
          GOOS=darwin GOARCH=amd64 go build -o ./build/darwin/onqlave .

      - name: Get release
        id: get-release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload Linux Release Asset
        id: upload-linux-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get-release.outputs.upload_url }}
          asset_path: ./build/linux/onqlave
          asset_name: onqlave-linux
          asset_content_type: application/octet-stream

      - name: Upload Darwin Release Asset
        id: upload-darwin-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get-release.outputs.upload_url }}
          asset_path: ./build/darwin/onqlave
          asset_name: onqlave-darwin
          asset_content_type: application/octet-stream